name: Merge main into develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config --global user.name ${{ vars.GIT_AUTHOR_NAME }}
          git config --global user.email ${{ vars.GIT_AUTHOR_EMAIL }}

      - name: Merge main into develop
        run: |
          git checkout develop
          git merge main --no-edit

      - name: Get Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(backport): automated backport [skip ci]"
          committer: ${{ vars.GIT_COMMITTER_NAME }} <${{ vars.GIT_COMMITTER_EMAIL }}>
          author: ${{ vars.GIT_AUTHOR_NAME }} <${{ vars.GIT_AUTHOR_EMAIL }}>
          title: "[skip ci] Backport changes from main"
          body: "This is an automated pull request to backport changes from main."
          branch: "automated-backport-${{ steps.date.outputs.date }}"
          base: 'develop'
          delete-branch: true
          labels: |
            automated
            backport