name: Update Community Health Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

env:
  COMMUNITY_HEALTH_GIT: https://github.com/wulfstack/community-health.git
  FILES_TO_COPY: '[
  "AUTHORS",
  "CODE_OF_CONDUCT.md",
  ".github/ISSUE_TEMPLATE/bug_report.md",
  ".github/ISSUE_TEMPLATE/documentation-issue.md",
  ".github/ISSUE_TEMPLATE/feature_request.md",
  ".github/ISSUE_TEMPLATE/question.md",
  ".github/PULL_REQUEST_TEMPLATE/pull_request_template.md",
  ".github/CODEOWNERS",
  ".github/FUNDING.yml"
  ]'
  BRANCH: 'develop'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    environment:
      name: Chore

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Checkout community health files
        uses: actions/checkout@v3
        with:
          repository: WulfStack/community-health
          path: ./tmp/community-health

      - name: Copy files
        run: |
          echo "## Checking Files" >> $GITHUB_STEP_SUMMARY
          for FILE in $(echo $FILES_TO_COPY | jq -r '.[]'); do
          mkdir -p $(dirname $FILE)
          if cp "./tmp/community-health/$FILE" ./$FILE; then
           echo "- ✅ $FILE" >> $GITHUB_STEP_SUMMARY
          else
           echo "::warning file=community-health/$FILE::File does not exist in the community health repository"
           echo "- ❌ $FILE (Missing)" >> $GITHUB_STEP_SUMMARY
          fi
          done
          rm -rf ./tmp

      - name: Check for changes
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only)
          echo "## Updated Files" >> $GITHUB_STEP_SUMMARY
          fileList=""
          hasChanged=false
          for FILE in $(echo $FILES_TO_COPY | jq -r '.[]'); do
            if [[ $CHANGED_FILES == *"$FILE"* ]]; then
              echo " - $FILE" >> $GITHUB_STEP_SUMMARY
              hasChanged=true
              fileList="${fileList}, - ${FILE}"
            fi
          done
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes were detected in the community health files." >> $GITHUB_STEP_SUMMARY
          fi
          formattedFileList=$(echo "$fileList" | tr ',' '\n')
          
          echo 'file-list<<EOF' >> $GITHUB_OUTPUT
          echo "${formattedFileList}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          
          echo "has-changed=${hasChanged}" >> $GITHUB_OUTPUT

      - name: Get Date
        id: date
        run: echo "date=date::$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.changes.outputs.has-changed == 'true'
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(community-health): automated update community health files [skip ci]"
          committer: ${{ vars.GIT_COMMITTER_NAME }} <${{ vars.GIT_COMMITTER_EMAIL }}>
          author: ${{ vars.GIT_AUTHOR_NAME }} <${{ vars.GIT_AUTHOR_EMAIL }}>
          title: "[skip ci] Update community health files"
          body: "This is an automated pull request to update the community health files.\n\n## Updated Files\n${{ steps.changes.outputs.file-list }}"
          branch: "automated-community-health-${{ steps.date.outputs.date }}"
          base: ${{ env.BRANCH }}
          delete-branch: true
          labels: |
            automated
            community-health

      - name: Create PR Summary
        if: steps.create_pr.outputs.pull-request-number
        run: |
          echo "## Pull Request" >> $GITHUB_STEP_SUMMARY
          echo "A pull request was created at [${{ steps.create_pr.outputs.pull-request-number }}](${{ steps.create_pr.outputs.pull-request-url }})." >> $GITHUB_STEP_SUMMARY
