name: Rebuild Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  BRANCH: 'develop'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    environment:
      name: Chore

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Rebuild Documentation
        run: npm run build:docs

      - name: Get Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(documentation): automated update documentation [skip ci]"
          committer: ${{ vars.GIT_COMMITTER_NAME }} <${{ vars.GIT_COMMITTER_EMAIL }}>
          author: ${{ vars.GIT_AUTHOR_NAME }} <${{ vars.GIT_AUTHOR_EMAIL }}>
          title: "[skip ci] Update documentation"
          body: "This is an automated pull request to update the documentation files."
          branch: "automated-documentation-${{ steps.date.outputs.date }}"
          base: ${{ env.BRANCH }}
          delete-branch: true
          labels: |
            automated
            documentation

      - name: Create PR Summary
        if: steps.create_pr.outputs.pull-request-number
        run: |
          echo "## Pull Request" >> $GITHUB_STEP_SUMMARY
          echo "A pull request was created at [${{ steps.create_pr.outputs.pull-request-number }}](${{ steps.create_pr.outputs.pull-request-url }})." >> $GITHUB_STEP_SUMMARY
